### ISSUE TITLE
Adapter bleibt gelb

### ISSUE THREAD

**Issue by Elmo127** [mrbungle64/ioBroker.switchbot-ble#1]
Hallo,

nachdem ich meinen Raspberry Pi 4 neu aufgesetzt habe bekomme ich den Adapter leider nicht mehr zum laufen. Hatte zuvor die Version 0.0.2 installiert. Diese lief ohne Probleme. Die Punkte in der Installationsanleitung habe bereits befolgt.

- Betriebssystem: Raspbian Buster light als Image von iobroker.net (doku)
- nodejs 12.20.0
- jscontroller 3.1.6

Das log bleibt auch unauffällig und meldet nur, dass der Adapter gestartet wurde.

Wie könnte ich weiter vorgehen? :)

Danke und Gruß

**Comment by mrbungle64** [comment]
Hallo @Elmo127,

was ich noch vergessen hatte zu fragen:
hast Du außer den 4 SwitchBots noch ein anderes Gerät von denen - z.B. ein "Curtain"?

**Comment by Elmo127** [comment]
Hey,Zu dem Zeitpunkt hatte ich lediglich einen Bot im Einsatz. Jetzt habe ich noch 4 Bots rumliegen die bis jetzt nicht im Einsatz sind :)Gesendet mit der GMX Mail AppAm 17.12.20 um 18:42 schrieb Sascha
                
            
            
                
                    Von: "Sascha" <notifications@github.com>Datum: 17. Dezember 2020An: "mrbungle64/ioBroker.switchbot-ble" <ioBroker.switchbot-ble@noreply.github.com>Cc: "Elmo127" <florian.weiss90@gmx.de>,"Mention" <mention@noreply.github.com>Betreff: Re: [mrbungle64/ioBroker.switchbot-ble] Adapter bleibt gelb (#1)
                
                

Hallo @Elmo127,

was ich noch vergessen hatte zu fragen:

hast Du außer den 4 SwitchBots noch ein anderes Gerät von denen - z.B. ein "Curtain"?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-747592239",

"url": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-747592239",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mrbungle64** [comment]
@Elmo127 

Der Raspberry Pi steht auch noch gleich weit entfernt vom (nächsten) SwitchBot?

Mit sieht es danach aus, als würde der von keinem Gerät eine Antwort bekommen.
Ein "echter" Fehler scheint ja dabie nicht aufzutreten.

**Comment by Elmo127** [comment]
Ich hab den sogar schon direkt davor gelegt 🤷🏼‍♂️Gesendet mit der GMX Mail AppAm 17.12.20 um 18:49 schrieb Sascha
                
            
            
                
                    Von: "Sascha" <notifications@github.com>Datum: 17. Dezember 2020An: "mrbungle64/ioBroker.switchbot-ble" <ioBroker.switchbot-ble@noreply.github.com>Cc: "Elmo127" <florian.weiss90@gmx.de>,"Mention" <mention@noreply.github.com>Betreff: Re: [mrbungle64/ioBroker.switchbot-ble] Adapter bleibt gelb (#1)
                
                

@Elmo127

Der Raspberry Pi steht auch noch gleich weit entfernt vom (nächsten) SwitchBot?

Mit sieht es danach aus, als würde der von keinem Gerät eine Antwort bekommen.

Ein "echter" Fehler scheint ja dabie nicht aufzutreten.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-747595864",

"url": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-747595864",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mrbungle64** [comment]
@Elmo127 

ok, ich muss wohl mal das Logging ein bischen erweitern - ich melde mich dann wieder.

Btw.: Ich habe mal Deine 2 Posts auf den eigentlichen Inhalt gekürzt - die waren so ein bisschen unübersichtlich weil das Reply per Email war ;)

**Comment by Elmo127** [comment]
Hallo,

Hab gerade unter den Bluetooth Geräten geschaut:

[CHG] Device FC:9E:91:E1:1E:E3 UUIDs: cba20d00-224d-11e6-9fb8-0002a5d5c51b
[CHG] Device FC:9E:91:E1:1E:E3 ServiceData Key: 00000d00-0000-1000-8000-00805f9b34fb
[CHG] Device FC:9E:91:E1:1E:E3 ServiceData Value:
  48 10 5d                                         H.]    

Diese Einträge betreffen den Swichtbot. Hilft dir das? 
Also erreichbar scheint er zu sein?

**Comment by mrbungle64** [comment]
@Elmo127 

Ja danke, das hilft zumindest soweit, dass wir nun wissen, dass die SwitchBots gefunden werden und auch Daten empfangen werden.

Da die eigentliche Kommunikation von den Libraries ([node-switchbot](https://www.npmjs.com/package/node-switchbot) beim Empfangen der Daten und [SwitchBot](https://www.npmjs.com/package/switchbot) zum Steuern der SwitchBot Bots) übernommen wird, bin ich ja jetzt nicht so drin in der Materie was Bluetooth betrifft ...
Der Adapter benutzt ja nur die jeweilige API der Libraries.

**Comment by mrbungle64** [comment]
Hallo @Elmo127 

probier' mal bitte, ob die Version 0.0.4 bei Dir funktioniert.
Ich habe dort die Version von der node-switchbot Library verwendet, die auch bei der Version 0.0.3 vom Adapter benutzt wurde.

**Comment by Elmo127** [comment]
Hallo,

leider unverändert ..

Grüße

**Comment by mrbungle64** [comment]
@Elmo127 

Hast Du schon mal versucht den Adapter zu deinstallieren und wieder neu zu installieren?

**Comment by Elmo127** [comment]
hab ich schon paar mal gemacht und jetzt gerade auch wieder. echt zum verzweifeln ..

**Comment by mrbungle64** [comment]
@Elmo127 

Ich habe ansonsten zwischen der Version 0.0.2 und 0.0.3 eigentlich nur
* bluetooth-hci-socket als dependency hinzufügt
* Code für den "Curtain" hinzufügt. Der sollte aber für die anderen beiden Modelle ungefährlich sein (und bei mir funktionierts ja auch)

Läuft die Installation eigentlich ohne Warnungen und Fehler durch?
Schau mal bitte was da kommt
1.) Wenn Du es neu installierst
2.) Wenn Du es installierst ohne vorher zu deinstallieren

**Comment by Elmo127** [comment]
Nein leider nichts alles in Ordnung

**Comment by mrbungle64** [comment]
@Elmo127 

> Nein leider nichts alles in Ordnung

Dann solltest Du das erst mal fixen ;)

**Comment by Elmo127** [comment]
da fehlt das Komma haha. Nein leider nichts, da ist alles in Ordnung :)

**Comment by mrbungle64** [comment]
@Elmo127 

Dumme Frage: hast Du vielleicht inzwischen ein Passwort für die Geräte in der Mobile App gesetzt?

**Comment by Elmo127** [comment]
nein hab ich nicht ..

**Comment by mrbungle64** [comment]
@Elmo127 

Ich habe in der Version 0.0.5 mal eine Option "scanDevicesWait" eingebaut (die bekommt noch einen sinnvolleren Namen).
Dort kannst Du mal ein bisschen ausprobieren, ob da einer der Werte besser ist als die Standardeinstellung.

Zusätzlich habe ich einen paar Meldungen im "debug" Modus eingebaut. Dazu müsstest Du das Loglevel für die Instanz auf "debug" ändern.

Mal schauen, ob wir so weiterkommen ;)

**Comment by Elmo127** [comment]
okay werd mich gleich mal dranmachen. Vielen Dank für die Unterstützung bis hierhin :)

**Comment by Elmo127** [comment]
also hier der Auszug aus dem Log:

switchbot-ble.0 | 2020-12-18 21:53:37.509 | debug | (9158) [execNextCmd] cmd: scanDevices
-- | -- | -- | --
switchbot-ble.0 | 2020-12-18 21:53:37.295 | debug | (9158) state switchbot-ble.0.info.connection changed: false (ack = true)
switchbot-ble.0 | 2020-12-18 21:53:37.256 | debug | (9158) [setNextInterval] interval: 250
switchbot-ble.0 | 2020-12-18 21:53:37.255 | debug | (9158) [setNextInterval] cmd: scanDevices
switchbot-ble.0 | 2020-12-18 21:53:37.209 | info | (9158) starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.switchbot-ble, node: v12.20.0, js-controller: 3.1.6
switchbot-ble.0 | 2020-12-18 21:53:36.896 | debug | (9158) statesDB connected
switchbot-ble.0 | 2020-12-18 21:53:36.894 | debug | (9158) States connected to redis: 127.0.0.1:9000
switchbot-ble.0 | 2020-12-18 21:53:36.587 | debug | (9158) States create System PubSub Client
switchbot-ble.0 | 2020-12-18 21:53:36.381 | debug | (9158) States create User PubSub Client
switchbot-ble.0 | 2020-12-18 21:53:36.333 | debug | (9158) Redis States: Use Redis connection: 127.0.0.1:9000
switchbot-ble.0 | 2020-12-18 21:53:36.330 | debug | (9158) objectDB connected
switchbot-ble.0 | 2020-12-18 21:53:36.322 | debug | (9158) Objects connected to redis: 127.0.0.1:9001
switchbot-ble.0 | 2020-12-18 21:53:35.750 | debug | (9158) Objects client initialize lua scripts
switchbot-ble.0 | 2020-12-18 21:53:35.748 | debug | (9158) Objects create User PubSub Client
switchbot-ble.0 | 2020-12-18 21:53:35.747 | debug | (9158) Objects create System PubSub Client
switchbot-ble.0 | 2020-12-18 21:53:35.609 | debug | (9158) Objects client ready ... initialize now
switchbot-ble.0 | 2020-12-18 21:53:35.152 | debug | (9158) Redis Objects: Use Redis connection: 127.0.0.1:9001

und das scanDevices (ganz oben in der ersten Zeile) macht er dann alle paar Millisekunden bis das ganze Log voll ist ... scheint sich da aufzuhängen bzw. macht das die ganze Zeit

**Comment by mrbungle64** [comment]
@Elmo127 

Hast Du die Adaptereinstellungen schon mal gespeichert und da jeweils einen Wert ausgewählt?

**Comment by Elmo127** [comment]
egal was ich einstelle im Adapter es ist immer so wie gerade beschrieben ..

**Comment by mrbungle64** [comment]
@Elmo127 

Probier bitte noch mal mit der aktuellen Version. Aber installiere den Adapter dabei noch mal neu bitte.

**Comment by Elmo127** [comment]
weiterhin unverändert er scannt in ner endlos schleife nach devices

**Comment by mrbungle64** [comment]
> weiterhin unverändert er scannt in ner endlos schleife nach devices

Ja, ich habe gerade gemerkt, dass der in diesen Zustand läuft, wenn der keine Devices findet.
Da scheint noch irgendwo ein Bug zu sein.

Bei Dir ist aber so oder so weiterhin das Problem dass der nix findet. Keine Ahnung woran das liegt.
Aber deswegen geht der bei Dir auch direkt in diesen Zustand rein.

**Comment by mrbungle64** [comment]
Hast Du eigentlich einen Hub für die SwitchBot Geräte?
Habe gerade gesehen, dass der Hersteller vor ein paar Tagen die API offengelegt hat:
https://github.com/OpenWonderLabs/SwitchBotAPI

Da kann sich jetzt jmd dran machen einen Adapter für zu entwickeln.
Dann muss man sich im Adapter nicht mehr mit Bluetooth rumschlagen ;)

**Comment by Elmo127** [comment]
ja schon komisch wenn der die Bluetooth Devices findet wenn ich sie manuell suche

**Comment by Elmo127** [comment]
ich hab mir den hub extra nicht gekauft weil ich gelesen habe, dass dieser (noch) nicht eingebunden werden kann :D

**Comment by mrbungle64** [comment]
> > weiterhin unverändert er scannt in ner endlos schleife nach devices
> 
> Ja, ich habe gerade gemerkt, dass der in diesen Zustand läuft, wenn der keine Devices findet.
> Da scheint noch irgendwo ein Bug zu sein.
> 
> Bei Dir ist aber so oder so weiterhin das Problem dass der nix findet. Keine Ahnung woran das liegt.
> Aber deswegen geht der bei Dir auch direkt in diesen Zustand rein.
> Bei mir ist es nicht so auffällig, weil er jeweils im nächsten Intervall wieder was findet.

Ich habe eben festgestellt, dass das eine andere Ursache hatte und nach einer Neuinstallation des Adapters durch eine falsche Einstellung in einem Datenpunkt  ausgelöst wurde.

Ich bin gerade ein bisschen ratlos was Dein Problem angeht ... 
Ich gehe im Moment davon aus, dass das Problem auf anderer Ebene ausgelöst wird.
Wie gesagt hatte sich der Adapter funktional zwischen 0.0.2 und 0.0.3 eigentlich nicht großartig geändert.
Da werden die Libraries den Unterschied machen ....

Ich hatte auch ehrlich gesagt die Existenz des Adapters nicht großartig verbreitet, weil ich schon die Vermutung hatte, dass es durch die Bluetooth Abhängigkeit nicht einfach werden wird das zu supporten. Ich habe da auch mit meinen Ecovacs Deebot Projekten schon mehr als genug zu tun, weil dort die API nicht offengelegt ist und es recht viele Modelle gibt ;)

Bei mir tut der Adapter wie gesagt das was er soll. Ich habe nur einen "Bot" und einen "Meter" und die funktionieren recht zuverlässig damit.
Jetzt wo die API für den Hub offengelegt wurde stehen die Chancen ja nicht schlecht, dass jemand auf dieser Grundlage einen neuen Adapter erstellt. Dann muss man sich dann wie gesagt nicht mehr mit Bluetooth rumschlagen ;)

**Comment by mrbungle64** [comment]
Hallo @Elmo127 

wie ist eigentlich gerade der Stand bei Dir und den SwitchBots?

Ich habe gesehen, dass jmd bei der hier verwendeten Library einen [Pull Request gestellt](https://github.com/futomi/node-switchbot/pull/17) hat, der ggf. auch bei Dir relevant sein könnte. Aber da müsste man erst noch abwarten was daraus wird.

Wärst Du dann noch interessiert oder hast Du inzwischen eine andere Lösung gefunden?

**Comment by Elmo127** [comment]
Hey Sascha,Sorry für die späte Antwort. Ich hab mir nen Hub und nen Meter gekauft und alles neu aufgesetzt. Jetz geht alles ohne Probleme :)Gruß Gesendet mit der GMX Mail AppAm 31.12.20 um 12:24 schrieb Sascha
                
            
            
                
                    Von: "Sascha" <notifications@github.com>Datum: 31. Dezember 2020An: "mrbungle64/ioBroker.switchbot-ble" <ioBroker.switchbot-ble@noreply.github.com>Cc: "Elmo127" <florian.weiss90@gmx.de>,"Mention" <mention@noreply.github.com>Betreff: Re: [mrbungle64/ioBroker.switchbot-ble] Adapter bleibt gelb (#1)
                
                

Hallo @Elmo127

wie ist eigentlich gerade der Stand bei Dir und den SwitchBots?

Ich habe gesehen, dass jmd bei der hier verwendeten Library einen Pull Request gestellt hat, der ggf. auch bei Dir relevant sein könnte. Aber da müsste man erst noch abwarten was daraus wird.

Wärst Du dann noch interessiert oder hast Du inzwischen eine andere Lösung gefunden?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-752930404",

"url": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-752930404",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mrbungle64** [comment]
@Elmo127 

> Ich hab mir nen Hub und nen Meter gekauft und alles neu aufgesetzt. Jetz geht alles ohne Probleme :)

Heißt das, dass es jetzt auch mit dem Adapter funktioniert?

**Comment by Elmo127** [comment]
Ja komischerweise schon Gesendet mit der GMX Mail AppAm 03.01.21 um 21:01 schrieb Sascha
                
            
            
                
                    Von: "Sascha" <notifications@github.com>Datum: 3. Januar 2021An: "mrbungle64/ioBroker.switchbot-ble" <ioBroker.switchbot-ble@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"Elmo127" <florian.weiss90@gmx.de>Betreff: Re: [mrbungle64/ioBroker.switchbot-ble] Adapter bleibt gelb (#1)
                
                

@Elmo127



Ich hab mir nen Hub und nen Meter gekauft und alles neu aufgesetzt. Jetz geht alles ohne Probleme :)



Heißt das, dass es jetzt auch mit dem Adapter funktioniert?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-753668700",

"url": "https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/1#issuecomment-753668700",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
