### ISSUE TITLE
Setting "Press state" to true does not trigger 

### ISSUE THREAD

**Issue by 1tb2** [mrbungle64/ioBroker.switchbot-ble#17]
Hi there!
First of all thanks a lot for this adapter! unfortunately, this does not work for with my system. Or i am doing something wrong.
Changing the state does not trigger any movement of the Switchbot bot arm. BLE identifies device correctly so far. Using Admin 5. any issues known?

Thanks upfront!

**Comment by mrbungle64** [comment]
Hi @1tb2 

have you already checked the log and the adapter settings?

* Wait while scanning devices (seconds) / Wartezeit während der Gerätesuche (Sekunden)
* Delay while retrying to  (milliseconds) / Auf Geräte warten (Millisekunden)

You may need to change these values

**Comment by 1tb2** [comment]
Hi mrbungle64, hi all,

thanks for the feedback. today I played around with the settings but nothing changed. I reinstalled and changed settings on proxmox vm. but nothing changed. finally I installed "Bluetooth-Niedrigenergie (BLE)" just to check if all functions are available and everything works. 

--> With parallel installation on "BLE"-Adapter, also the Switchbot is working. as soon I uninstall or stop the adapter in iobroker. Switchbot is not movin anymore. 

This of course is not a real fix but maybe it helps to understand the root cause. at least a workaround...

Thanks for support!
1TB2

**Comment by mrbungle64** [comment]
> Hi mrbungle64, hi all,

Hi @1tb2 

thanks for the information 👍🏻 

> 
> thanks for the feedback. today I played around with the settings but nothing changed. I reinstalled and changed settings on proxmox vm. but nothing changed. finally I installed "Bluetooth-Niedrigenergie (BLE)" just to check if all functions are available and everything works.
> 
> --> With parallel installation on "BLE"-Adapter, also the Switchbot is working. as soon I uninstall or stop the adapter in iobroker. Switchbot is not movin anymore.

Sounds very interesting.
I also had already installed the ble adapter but without a running instance (therefore the instance was not started)
Is it reproducible that starting and stopping the ble adapter affects whether it is possible to move the Switchbot "Bot"?

> 
> This of course is not a real fix but maybe it helps to understand the root cause. at least a workaround...
> 
> Thanks for support!
> 1TB2

**Comment by m0uh85** [comment]
Gleiches Problem hier. 
Gerät wird angezeigt aber bei "Tasten-Druck" keinerlei Reaktion oder Funktion.

**Comment by mrbungle64** [comment]
@1tb2

Does the problem still exist?

> Is it reproducible that starting and stopping the ble adapter affects whether it is possible to move the Switchbot "Bot"?

Still waiting for feedback 😉

**Comment by mrbungle64** [comment]
@m0uh85 

> Gleiches Problem hier. Gerät wird angezeigt aber bei "Tasten-Druck" keinerlei Reaktion oder Funktion.

Gibt es ein paar mehr Infos für mich? 😉

**Comment by m0uh85** [comment]
> @m0uh85
> 
> > Gleiches Problem hier. Gerät wird angezeigt aber bei "Tasten-Druck" keinerlei Reaktion oder Funktion.
> 
> Gibt es ein paar mehr Infos für mich? 😉

Gerne...  doch :)
Version: 0.2.3
Node.js v12.22.7

also Objekte sind alle richtig angelegt und erreichbar.... betätige ich unter Control bei "Press" den Button - tut sich nix
Zeitstempel ändert sich aber unter Bestätigt der Zeitstempel bleibt gleich.

Habe auch probiert den BLE Adapter mal zu installieren, aber gleiches Problem.

LOG:
<html>
<body>


switchbot-ble.0 | 2021-11-15 18:36:55.595 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-15 18:36:54.023 | warn | Will try again in 5000 milliseconds ...
switchbot-ble.0 | 2021-11-15 18:36:54.022 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: undefined
switchbot-ble.0 | 2021-11-15 18:36:48.736 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-15 18:36:47.034 | warn | Will try again in 5000 milliseconds ...
switchbot-ble.0 | 2021-11-15 18:36:47.033 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: undefined


</body>
</html>

**Comment by mrbungle64** [comment]
@m0uh85 

Probier mal bitte folgendes auf dem System wo der ioBroker installiert ist:

```bash
cd /opt/iobroker/node_modules/switchbot/
node
```

```js
const Switchbot = require('switchbot');
const switchbot = Switchbot('e1:b1:f4:7b:67:0b');
switchbot.press();
```

**Comment by mrbungle64** [comment]
@1tb2 @m0uh85 

I just released version 0.3.0

Please try if it's working now

**Comment by m0uh85** [comment]
Also kurzes Feedback von meiner Seite. Als ich deine Eingabe getestet habe kam bei den beiden 
const Switchbot = require('switchbot');
const switchbot = Switchbot('e1:b1:f4:7b:67:0b');
Jeweils irgendwas mit undefined (kann ich dir leider nicht mehr genau sagen hab ich heute Nacht im halb schlaf getestet.) ABER
switchbot.press();
wurde ausgeführt und hat funktioniert. So danach hab ich es über den iobroker getestet... hat auch funktioniert. Heute Morgen hab ich so 12-15 Schaltvorgänge getestet alle haben funktioniert.
Seeeeeeeeeehr komisch!
Werde jetzt trotzdem mal updaten und schauen wie es läuft die Tage....

**Comment by m0uh85** [comment]
switchbot-ble.0 | 2021-11-16 19:45:40.132 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Now connecting. Wait for a few seconds then try again.
-- | -- | -- | --
switchbot-ble.0 | 2021-11-16 19:45:09.175 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Now connecting. Wait for a few seconds then try again.



switchbot-ble.0 | 2021-11-16 19:44:26.989 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Now connecting. Wait for a few seconds then try again.
-- | -- | -- | --
switchbot-ble.0 | 2021-11-16 19:44:09.807 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:43:47.331 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:43:31.557 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: TypeError: Cannot read property 'press' of undefined
switchbot-ble.0 | 2021-11-16 19:43:23.219 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:43:15.417 | info | Device e1:b1:f4:7b:67:0b pressed

**Comment by mrbungle64** [comment]
@m0uh85 

Änder' mall bitte "Wartezeit für erfolgreiches Bewegen vom Arm des Bots" auf 10 Sekunden (falls noch nicht geschehen)

**Comment by m0uh85** [comment]
switchbot-ble.0 | 2021-11-16 20:26:36.699 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-16 20:26:20.892 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-16 20:25:49.616 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 20:25:27.566 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-16 20:20:12.244 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:54:33.549 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:53:58.870 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-16 19:53:40.025 | info | Device e1:b1:f4:7b:67:0b pressed

**Comment by mrbungle64** [comment]
@m0uh85 

Die Fehler (`No service was found`) werden von der Library gemeldet.

Ich habe noch mal 15 und 20 Sekunden als Auswahl hinzugefügt.

**Comment by m0uh85** [comment]
0.3.1 - 20 Sekunden:
<html>
<body>


switchbot-ble.0 | 2021-11-17 10:03:19.032 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-17 10:03:03.533 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-17 10:02:42.833 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-17 10:01:31.803 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-17 08:47:35.606 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-17 08:33:22.388 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-17 08:18:26.191 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-17 08:16:46.858 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-17 08:11:42.118 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-17 08:07:39.676 | info | Device e1:b1:f4:7b:67:0b pressed


</body>
</html>

**Comment by mrbungle64** [comment]
@m0uh85 

Ich denke dass ich das Problem gefunden habe ...
Gibt dann so bald wie möglich ein Update.

Aktuell sollte es am besten sein, wenn man den Wert von "Wartezeit während der Gerätesuche" auf 1 Sekunde stellt und das "Intervall für die Gerätesuche" auf 15 Sekunden.

**Comment by mrbungle64** [comment]
@m0uh85 

Ich habe eben die Version 0.3.2 veröffentlicht.

Damit sollte es nun deutlich zuverlässiger funktionieren. Bei einem Fehler wird der Befehl erneut ausgeführt.

"Intervall für die Gerätesuche" kann nun wieder auf deutlich unter 60 Sekunden (z.B. 15 Sekunden)

**Comment by m0uh85** [comment]
@mrbungle64 ich update schnell und schreib dann schnell ein Blockly das der Taster alle 15 Minuten mal betätigt wird. Melde mich dann am Nachmittag mit dem Ergebnis.

**Comment by m0uh85** [comment]
Intervall für die Gerätesuche (Sekunden): 15
Wartezeit während der Gerätesuche (Sekunden): 1
Wartezeit für erfolgreiches Bewegen vom Arm des Bots (Sekunden): 20 

oder soll ich andere Werte testen?

**Comment by m0uh85** [comment]
<html>
<body>


switchbot-ble.0 | 2021-11-18 09:00:02.414 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-18 08:45:02.468 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 08:42:47.669 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 08:40:27.098 | info | Device detected: e1:b1:f4:7b:67:0b


</body>
</html>

9:15 & 9:30 & 9:45 Uhr wurde nicht ausgeführt.... zwischenzeitlich habe ich auch 3-4x manuell gedrückt und keine Funktion. Im Log habe ich keine Warn- bzw. Fehlermeldung.

**Comment by m0uh85** [comment]
Also wie du siehst läuft es zwar nicht fehlerfrei ABER nach einem Error wird der Bot dann trotzdem ausgelöst.
Was vllt. cool wäre, wenn man diese Info "Device e1:b1:f4:7b:67:0b pressed" also Rückmeldung per Objekt - State bekommen würde. 

<html>
<body>


switchbot-ble.0 | 2021-11-18 12:45:03.823 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-18 12:30:02.973 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 12:15:07.502 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 12:15:04.283 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 12:00:06.373 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 11:45:10.153 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 11:45:06.093 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 11:45:03.698 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 11:45:01.713 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 11:30:09.274 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 11:30:02.151 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 11:15:05.428 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 11:00:06.982 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 11:00:04.043 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 11:00:01.763 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 10:45:02.784 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 10:30:04.272 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 10:15:07.678 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 10:15:03.983 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 10:15:01.364 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 10:00:07.261 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 09:57:07.779 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 09:52:25.077 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 09:52:09.499 | info | Device detected: e1:b1:f4:7b:67:0b


</body>
</html>

**Comment by m0uh85** [comment]
Sieht doch bisher ganz OK aus :) 

<html>
<body>


switchbot-ble.0 | 2021-11-18 18:30:02.683 | info | Device e1:b1:f4:7b:67:0b pressed
-- | -- | -- | --
switchbot-ble.0 | 2021-11-18 18:15:07.713 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 18:15:03.753 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 18:00:03.555 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 17:45:03.085 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 17:30:02.873 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 17:15:06.861 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 17:15:01.792 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 17:00:03.336 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 16:45:02.797 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 16:30:02.393 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 16:15:02.862 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 16:00:02.776 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 15:45:06.032 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 15:45:02.175 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: No service was found.
switchbot-ble.0 | 2021-11-18 15:30:03.191 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 15:15:02.992 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 15:00:02.377 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 14:45:05.128 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 14:45:01.913 | warn | Error while running deviceAction press for device e1:b1:f4:7b:67:0b: Error: Failed to discover services and characteristics: DISCONNECTED
switchbot-ble.0 | 2021-11-18 14:30:02.758 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 14:23:28.359 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 14:15:02.700 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 14:00:05.331 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 13:45:03.273 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 13:30:02.982 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 13:15:02.680 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 13:00:02.800 | info | Device e1:b1:f4:7b:67:0b pressed
switchbot-ble.0 | 2021-11-18 12:49:09.985 | info | Device e1:b1:f4:7b:67:0b pressed


</body>
</html>

**Comment by mrbungle64** [comment]
@m0uh85 

> Sieht doch bisher ganz OK aus :)

Ja, sieht so aus als wären die alle erfolgreich gewesen 👍🏻 

> Was vllt. cool wäre, wenn man diese Info "Device e1:b1:f4:7b:67:0b pressed" also Rückmeldung per Objekt - State bekommen würde.

Hast du eine Idee wie man das abbilden könnte?

**Comment by mrbungle64** [comment]
@m0uh85 

Ich habe eben Version 0.3.3
Die Anzahl der Wiederholungen ist nun auf 15 begrenzt und die Protokollierung sollte ein bisschen detaillierter und klarer sein.
