### ISSUE TITLE
connection to switchbot available, but pressing buttons in objects list of iobroker has no impact

### ISSUE THREAD

**Issue by Zurbud** [mrbungle64/ioBroker.switchbot-ble#173]
### The question

Hi, thanks for providing this nice adapter for the community! I installed it on my pi and it connected smoothly to the switchbot (bot). I can see the correct device ID in iobroker (objects -> switchbot-ble -> 0 -> <BLE MAC> -> devideInfo and hence expected that I can just use the buttons in "control" tree. But pressing them leads to no result. Not sure where/how I could do some additional trouble shooting... hence, came to this place ;-) 
Thanks again for your help

### Additional information

iobroker host version 4.0.23
Node.js v12.22.12
NPM 6.14.16
switchbot-ble 0.4.3
Switchbot bot firmware: 4.9

**Comment by mrbungle64** [comment]
@Zurbud 

Can you please post some log output?

Please make also sure that you don't check "Acknowledged"/"Bestätigt" when running the command.

**Comment by Zurbud** [comment]
Thanks for your quick response! In the meantime I tried the following:
- moved pi closer to switchbot bot to ensure I don't have a bluetooth range issue -> no change in behaviour
- checked that I don't have acknowledged checked -> checkbox is not checked
- log does not return anything when a button is pressed (e.g. "turnOff")

These are the only entries I get in the log (you can see that I restarted the instance once):

switchbot-ble.0
2022-07-10 15:21:17.355	info	[deviceAction] SwitchBot Bot (c8:a0:7f:85:2a:7d) already turned on
switchbot-ble.0
2022-07-10 15:20:47.789	info	[scanDevices] device detected: SwitchBot Bot (c8:a0:7f:85:2a:7d)
switchbot-ble.0
2022-07-10 15:20:37.403	info	Set the NOBLE_HCI_DEVICE_ID environment variable to 0 (hci0)
switchbot-ble.0
2022-07-10 15:20:37.360	info	starting. Version 0.4.3 in /opt/iobroker/node_modules/iobroker.switchbot-ble, node: v12.22.12, js-controller: 4.0.23
switchbot-ble.0
2022-07-10 15:20:32.106	info	Got terminate signal TERMINATE_YOURSELF
switchbot-ble.0
2022-07-10 15:15:49.565	info	[deviceAction] SwitchBot Bot (c8:a0:7f:85:2a:7d) already turned on
switchbot-ble.0
2022-07-10 15:15:38.273	info	[botAction] SwitchBot Bot (c8:a0:7f:85:2a:7d) successfully turned off

I added a screenshot of how it looks like in my objects list, as I suspect that the adapter perhaps found the bot once, but then is no longer receiving updating the values? I imagine they would not always show "true"? But I'm just guessing here...

Thanks again so much!
![image](https://user-images.githubusercontent.com/32640497/178146966-6166ad58-5437-41ef-9bc6-394060565cac.png)

**Comment by mrbungle64** [comment]
@Zurbud 

Have you already executed this command (again)?

```bash
$ sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
```

**Comment by Zurbud** [comment]
yes, I had done that during installation. Also, ran it now again just to make sure. Looks like deviceInfo gets set now, but the rest is still without response when I set to "true".
I'm on node v12 and could try to upgrade to the recommended version you suggest... 

![image](https://user-images.githubusercontent.com/32640497/178153612-dccc9c8f-a9b0-42cf-b853-b2e6d9f2ec15.png)

**Comment by mrbungle64** [comment]
@Zurbud 
Have you already tried other values for the various options in the settings?

**Comment by mrbungle64** [comment]
@Zurbud 

> I'm on node v12 and could try to upgrade to the recommended version you suggest...

Node.js version 12 should work fine

**Comment by mrbungle64** [comment]
@Zurbud 

Do you also use the BLE adapter? This could cause this problems.

**Comment by Zurbud** [comment]
I just now had the first successful change of the bot via a change of turnOff after I played with the parameters in settings as you suggested. I also increased the visibility of the log to "silly" so that I can see what else is going on. Should have done that earlier. Let me play around a bit more, I will update with results. I think I'm slowly getting there. Thanks a ton for your kind help!

**Comment by Zurbud** [comment]
> @Zurbud
> 
> Do you also use the BLE adapter? This could cause this problems.

no, I only installed the bluetooth libraries for this adapter.
