### ISSUE TITLE
Is SwitchBot Meter Plus (Thermometer and Hygrometer Plus) supported

### ISSUE THREAD

**Issue by WilliW610** [mrbungle64/ioBroker.switchbot-ble#175]
### The question

Hello together,

first of all, thank you for providing this adapter. I use it on ioBroker, Raspberry Pi 4.

I just bought a bunch of SwitchBots, now I discovered, that the adapter does not connect to my SwitchBot Meter Plus.
The connection to my SwitchBot Bot works fine, even though it takes a long while, after restarting the adapter/instance.

Should the SwitchBot Meter Plus already work? If No, is the implementation to support the SwitchBot Meter Plus planned?

Thank you and best regards,
WilliW610

**Comment by mrbungle64** [comment]
Hi @WilliW610,

the SwitchBot Meter Plus seems to be supported by the latest version of the library (v1.3.0).
I'll try to release a new version of the adapter this weekend.

**Comment by WilliW610** [comment]
Hi @mrbungle64,

thank you for the quick response, I appreciate that! After updating to the new version, I can feedback, if the Meter Plus is working.

**Comment by mrbungle64** [comment]
@WilliW610 

Please try version 0.4.4 😃

**Comment by WilliW610** [comment]
@mrbungle64 

It perfectly works with version 0.4.4! Thank you for your efforts!
