### ISSUE TITLE
(773060) Error deviceAction: undefined

### ISSUE THREAD

**Issue by Buddinski88** [mrbungle64/ioBroker.switchbot-ble#2]
Hi,

danke erst mal für den Adapter. Genau das was ich gesucht habe, denn jetzt kann ich die Kaffeemaschiene, welche es für meine Frau zu  Weihnachten gibt, noch smart machen 👍 

Soweit funktioniert der Adapter, aber im Log werden immer folgende Zeilen angezeigt, wenn ich den Switchbot triggere:

```
switchbot-ble.0 | 2020-12-19 05:35:42.417 | info | (773060) device c9:61:75:8e:5b:02 pressed
-- | -- | -- | --
switchbot-ble.0 | 2020-12-19 05:35:42.378 | info | (773060) device c9:61:75:8e:5b:02 pressed
switchbot-ble.0 | 2020-12-19 05:35:42.318 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:42.229 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:42.119 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:42.021 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.928 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.830 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.730 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.651 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.514 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.310 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.209 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.107 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:41.008 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:40.923 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:40.806 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:40.706 | error | (773060) Error deviceAction: undefined
switchbot-ble.0 | 2020-12-19 05:35:40.606 | error | (773060) Error deviceAction: undefined
```

Ist das normal?

Viele Grüße

**Comment by mrbungle64** [comment]
> Hi,
> 
> danke erst mal für den Adapter. Genau das was ich gesucht habe, denn jetzt kann ich die Kaffeemaschiene, welche es für meine Frau zu Weihnachten gibt, noch smart machen 

Hi @Buddinski88 

freut mich, dass ich Euch zu Weihnachten eine Freude machen kann mit dem Adapter 👍🏻 

> 
> Soweit funktioniert der Adapter, aber im Log werden immer folgende Zeilen angezeigt, wenn ich den Switchbot triggere:
> 
> ```
> switchbot-ble.0 | 2020-12-19 05:35:42.417 | info | (773060) device c9:61:75:8e:5b:02 pressed
> -- | -- | -- | --
> switchbot-ble.0 | 2020-12-19 05:35:42.378 | info | (773060) device c9:61:75:8e:5b:02 pressed
> switchbot-ble.0 | 2020-12-19 05:35:42.318 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:42.229 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:42.119 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:42.021 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.928 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.830 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.730 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.651 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.514 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.310 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.209 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.107 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:41.008 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:40.923 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:40.806 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:40.706 | error | (773060) Error deviceAction: undefined
> switchbot-ble.0 | 2020-12-19 05:35:40.606 | error | (773060) Error deviceAction: undefined
> ```
> 
> Ist das normal?
> 
> Viele Grüße

Ich nehme mal an, dass Du den Bot im "Press mode" betreibst, oder?

Es kann sein, dass ich für diesen Modus noch was ändern muss.
Ich selbst habe nur einen Bot der aber im "Switch mode" geschaltet ist.
Ich versuche das trotzdem mal zu testen und die o.g. Meldung zu fixen.

**Comment by Buddinski88** [comment]
@mrbungle64, danke für die schnelle Antwort.

Genau du hast es richtig erkannt, ich betreibe den Bot im "Press mode". Funktionieren tut ja alles, aber wenn man das Log "sauber" bekommt, dann wäre es ne Runde Sache.

**Comment by mrbungle64** [comment]
Hallo @Buddinski88 

Ich habe in den Einstellungen noch eine Option "Auf Geräte warten (Millisekunden)" eingebaut.
Bisher waren das fest (nur) 50 millisekunden. Wahrscheinlich ist es besser das auf einen Wert >= 1000 zu stellen.
Zusätzlich habe ich diesbezüglich noch einen Bug gefixt und die Fehlermeldung auf eine Warnung geändert und den Text dazu angepasst um ein bisschen klarer zu machen, was da eigentlich gerade passiert.
Das Ganze ist leider ein bisschen tricky, weil ich über die Library nicht direkt eine Rückmeldung bekomme, ob das Schalten erfolgreich war. Daher musste ich da ein bisschen tricksen.

Schau mal bitte, ob sich das damit nun "angenehmer" im Ergebnis gestaltet.

**Comment by Buddinski88** [comment]
Hi @mrbungle64,

erst mal noch frohe Weihnachten (daher melde ich mich auch jetzt erst).

Ich habe eben das Update auf Version 0.0.6 ausgeführt und die Option "Auf Geräte warten" auf 1000 gesetzt.
Nun taucht im Log nur noch einmal die Meldung (WARN) auf, was das ganze deutlich angenehmer macht 👍 
Ich denke das ist jetzt gut gelöst, sofern die Library einfach nicht mehr hergibt.

Danke dir an der Stelle noch mal!

Hier noch das Log:


```
switchbot-ble.0 | 2020-12-26 04:57:06.907 | info | (796363) device c9:61:75:8e:5b:02 pressed
-- | -- | -- | --
switchbot-ble.0 | 2020-12-26 04:57:06.683 | info | (796363) device c9:61:75:8e:5b:02 pressed
switchbot-ble.0 | 2020-12-26 04:57:04.884 | warn | (796363) Error while deviceAction press. Will try again in 1000 milliseconds ...
switchbot-ble.0 | 2020-12-26 04:56:58.897 | info | (796363) Detected device: c9:61:75:8e:5b:02
switchbot-ble.0 | 2020-12-26 04:56:57.682 | info | (796363) starting. Version 0.0.6 in /opt/iobroker/node_modules/iobroker.switchbot-ble, node: v12.20.0, js-controller: 3.1.6
host.iobroker-prod | 2020-12-26 04:56:56.192 | info | instance system.adapter.switchbot-ble.0 started with pid 796363
host.iobroker-prod | 2020-12-26 04:56:56.126 | info | "system.adapter.switchbot-ble.0" enabled
```

Ich schließe das Ticket an der Stelle dann mal.
