### ISSUE TITLE
[scanDevices] error: Error: Failed to initialize the Noble object: poweredOff

### ISSUE THREAD

**Issue by miael123** [mrbungle64/ioBroker.switchbot-ble#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,
habe den Adapter erfolgreich installiert und meinen switchbot Bot genutzt.
Um den bluetooth Empfang zu verbesseren habe ich den Pi runtergefahren und an einen neuen Ort neu gestartet.
Seitdem ist die Instanz gelb.
`Failed to initialize the Noble object: poweredOff`
Der Fehler deutet auf bluetooth Probleme hin. Habe hier schon mehrere Sachen probiert jedoch ohne Erfolg.

Kann mir einer als nobe nochmal einen Hinweis geben?

Bluetooth Status:

`iobroker@iobroker:/opt/iobroker/node_modules/iobroker.switchbot-ble $ sudo systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2022-10-31 19:54:13 CET; 48min ago
     Docs: man:bluetoothd(8)
 Main PID: 468 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/bluetooth.service
           └─468 /usr/lib/bluetooth/bluetoothd

Oct 31 19:54:12 iobroker systemd[1]: Starting Bluetooth service...
Oct 31 19:54:13 iobroker bluetoothd[468]: Bluetooth daemon 5.50
Oct 31 19:54:13 iobroker systemd[1]: Started Bluetooth service.
Oct 31 19:54:13 iobroker bluetoothd[468]: Starting SDP server
Oct 31 19:54:13 iobroker bluetoothd[468]: Bluetooth management interface 1.18 initialized
iobroker@iobroker:/opt/iobroker/node_modules/iobroker.switchbot-ble $`

Danke!

### Version of the JS controller

v16.18.0

### Version of Node.js

v16.18.0

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
Plattform: linux
    RAM: 3.7 GB
    Node.js: v16.18.0
    NPM: 8.19.2
```

**Comment by miael123** [comment]
Troubleshooting natürlich auch schon mehrmals gemacht.
Einzig seltsam:
 auf 
`sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`
gibt es keine Rückmeldung

**Comment by mrbungle64** [comment]
@miael123 

> Troubleshooting natürlich auch schon mehrmals gemacht. Einzig seltsam: auf `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)` gibt es keine Rückmeldung

Das ist normal - da gibt es leider keine Rückmeldung 😉

**Comment by mrbungle64** [comment]
@miael123 

Schon mal den Adapter komplett neu installiert?

**Comment by miael123** [comment]
Danke für die Rückmeldung. 
Neu installiert hat nicht geholfen. Hab sogar ein Backup reingespielt.

iobroker@iobroker:~ $ rfkill list
0: phy0: Wireless LAN
  Soft blocked: no
  Hard blocked: no
1: hci0: Bluetooth
  Soft blocked: no
  Hard blocked: no
iobroker@iobroker:~ $

**Comment by miael123** [comment]
Moin,
nach einer Stunde ausprobieren funktioniert es wieder.
Eine Ursache konnte ich aber nicht zuordnen.
Habe diverse ergoogelte Befehle genutzt...
update, upgrate, fixer und die ganzen BLE sachen...

Schönen Sonntag!
