### ISSUE TITLE
Adapter bleibt gelb nach Installation

### ISSUE THREAD

**Issue by Maverick3008** [mrbungle64/ioBroker.switchbot-ble#3]
Ich habe den Adapter installiert und es sah alles zunächst gut aus.
Der Adapter bleibt allerdings gelb. Der ioBroker BLE Adapter funktioniert ohne Probleme. 

Das System läuft auf einem Raspberry Pi 4. 

Den Befehl habe ich schon ausgeführt: sudo setcap cap_net_raw+eip $(eval readlink -f which node))

switchbot-ble.0 | 2021-01-29 13:12:02.518 | debug | (8266) [setNextInterval] cmd: scanDevices
switchbot-ble.0 | 2021-01-29 13:12:02.518 | debug | (8266) [scanDevices] setNextInterval: true
switchbot-ble.0 | 2021-01-29 13:12:02.516 | debug | (8266) [execNextCmd] cmd: scanDevices
switchbot-ble.0 | 2021-01-29 13:11:52.519 | debug | (8266) [setNextInterval] cmd: scanDevices
switchbot-ble.0 | 2021-01-29 13:11:52.518 | debug | (8266) [scanDevices] setNextInterval: true
switchbot-ble.0 | 2021-01-29 13:11:52.516 | debug | (8266) [execNextCmd] cmd: scanDevices
switchbot-ble.0 | 2021-01-29 13:11:42.531 | debug | (8266) system.adapter.admin.0: logging true
switchbot-ble.0 | 2021-01-29 13:11:42.085 | debug | (8266) state switchbot-ble.0.info.connection changed: false (ack = true)
switchbot-ble.0 | 2021-01-29 13:11:42.036 | debug | (8266) [setNextInterval] interval: 250
switchbot-ble.0 | 2021-01-29 13:11:42.035 | debug | (8266) [setNextInterval] cmd: scanDevices
switchbot-ble.0 | 2021-01-29 13:11:42.002 | info | (8266) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.switchbot-ble, node: v12.20.1, js-controller: 3.1.6

**Comment by mrbungle64** [comment]
@Maverick3008 

Wenn der BLE Adapter funktioniert sollte es ja grundsätzlich klappen.
Kannst Du mal bitte Version 0.1.0 installieren - die kann man ja noch über das +-Symbol im Expertenmodus installieren.

**Comment by Maverick3008** [comment]
Wenn ich versuche ein Downgrade zu machen kommt:

$ ./iobroker upgrade switchbot-ble@0.1.0
Adapter "switchbot-ble" is not in the repository and cannot be updated.
process exited with code 0

**Comment by mrbungle64** [comment]
> Wenn ich versuche ein Downgrade zu machen kommt:
> 
> $ ./iobroker upgrade switchbot-ble@0.1.0
> Adapter "switchbot-ble" is not in the repository and cannot be updated.
> process exited with code 0

@Maverick3008 
Deswegen hatte ich ja auch geschrieben

> ... die kann man ja noch über das +-Symbol im Expertenmodus installieren.

**Comment by Maverick3008** [comment]
![image](https://user-images.githubusercontent.com/29688840/106287312-f1dda680-6246-11eb-959a-4c5e01c9632f.png)
 Hier habe ich das versucht. Ist das falsch ?

**Comment by mrbungle64** [comment]
> ![image](https://user-images.githubusercontent.com/29688840/106287312-f1dda680-6246-11eb-959a-4c5e01c9632f.png)
> Hier habe ich das versucht. Ist das falsch ?

Ja das ist schon korrekt so.
Sorry das war mein Fehler. Dazu muss es ja auf npm veröffentlicht sein und das ist es in diesem Fall ja nicht.
Ich dachte erst Du hättest das so auf dem Terminal versucht zu installieren.

**Comment by mrbungle64** [comment]
@Maverick3008 

Du kannst mal versuchen ob es besser funktioniert, wenn Du in den Adapter Einstellungen den Wert für "Auf Geräte warten (Millisekunden)" höher stellst.

**Comment by Maverick3008** [comment]
Habe ich auf Maximum gestellt. Auch habe ich versucht das ganze mal auf einem zweiten Raspi zu installieren. Da habe ich das gleiche Problem.

**Comment by mrbungle64** [comment]
@Maverick3008 
Welche Geräte hast Du eigentlich?

**Comment by Maverick3008** [comment]
@mrbungle64 
Ich habe einen Switchbot Bot bestellt. Aber der ist noch nicht da. 
Daher ja die Frage, ob der Adapter auch ohne Geräte grün werden müsste.

**Comment by mrbungle64** [comment]
@Maverick3008 
Achso, das hatte ich falsch verstanden 😉 
Also noch mal von vorne:
der geht erst auf grün, wenn mind. ein Gerät gefunden wurde

**Comment by Maverick3008** [comment]
Ach sorry, Vielleicht habe ich mich da blöd ausgedrückt. Trotzdem danke für deine Hilfe. 
Dann hoffe ich mal, dass das Bot schnell kommt ;-)

**Comment by mrbungle64** [comment]
Kein Problem, dann schließen wir den Issue erst mal.
Sollte der Bot nicht erkannt werden kannst Du den Issue ja noch mal öffnen.
