### ISSUE TITLE
Switchbots don't work from time to time

### ISSUE THREAD

**Issue by zoulhh** [mrbungle64/ioBroker.switchbot-ble#316]
### The question

-ble.0
2023-04-23 09:42:33.402	error	[botAction] max. retries (5) reached. Giving up ...

switchbot-ble.0
2023-04-23 09:42:33.402	warn	[botAction] error while running 'up' for SwitchBot Bot (c4:39:35:44:9f:d2): Discover deviceList is empty!: Discover deviceList is empty!

I raised the retries to 25 meanwhile. This error happens from time to time. Any idea?

Thank you.

**Comment by mrbungle64** [comment]
@zoulhh 

> This error happens from time to time

How often does this happen?

**Comment by zoulhh** [comment]
> @zoulhh
> 
> > This error happens from time to time
> 
> How often does this happen?

Several times a day even though I don't switch too often. Maybe 10 times a day. Happens with different Switchbots.

Thank you.

Mick

**Comment by mrbungle64** [comment]
@zoulhh 

Do you have another application running on the same system that is also using Bluetooth?

**Comment by zoulhh** [comment]
> @zoulhh
> 
> Do you have another application running on the same system that is also using Bluetooth?

No.

**Comment by mrbungle64** [comment]
@zoulhh 

If you're using the GitHub version please try the latest version via npm (v0.4.5)

**Comment by zoulhh** [comment]
> @zoulhh
> 
> If you're using the GitHub version please try the latest version via npm (v0.4.5)

Thanks for the response. I am not very familiar to linux. Can you please explain what to do? Thank you.

**Comment by mrbungle64** [comment]
@zoulhh 

Open a terminal on your system where ioBroker is installed.
Change to the ioBroker installation directory. On most systems, this should be /opt/iobroker. 
```bash
cd /opt/iobroker
```
Note: If your installation directory is different, change the path accordingly.

Install the adapter from npm using the following command:
```
npm install iobroker.switchbot-ble
```

**Comment by mrbungle64** [comment]
@zoulhh 

Did it work?
