### ISSUE TITLE
After each restart the adapter is red - normal?

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.switchbot-ble#383]
### The question

Hello,

I have to run these lines after **each** reboot:

```
$ cd /opt/iobroker/node_modules/iobroker.switchbot-ble/
$ sudo rm -r node_modules/
$ npm install
$ sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
```

This is impractical. Is the behavior correct? Is it possible to automate this?

The version displayed in iobroker is 0.4.3 and this is also installed.

Many greetings
Leif

**Comment by mrbungle64** [comment]
@capitaenz

Hi Leif, sorry for late reply 🙏🏻 

> I have to run these lines after each reboot:

Do you really have to delete the `node_modules` (and run `npm install`) folder in this case?
I don't think I've ever experienced that with my system.

**Comment by mrbungle64** [comment]
@capitaenz 

Please try the latest version of the adapter (1.4.7-alpha.x).
Maybe your issue is caused by an older version of the @abandonware/noble library.

**Comment by capitaenz** [comment]
@mrbungle64 
Thank you for your answer and help.
I have installed the new version and an update with reboot is coming soon, I will report back.

Greetings
Leif

**Comment by capitaenz** [comment]
Apologies for the late reply.
The problem still persists, it helps to run this:

`
$ cd /opt/iobroker/node_modules/iobroker.switchbot-ble/
$ sudo rm -r node_modules/
$ npm install
`
Version 0.4.7 is installed.

How can I contribute to the solution?

**Comment by mrbungle64** [comment]
@capitaenz 

> The problem still persists, it helps to run this:

Has this solved the problem so far or does it still exist?

**Comment by capitaenz** [comment]
@mrbungle64 
I have to restart the installation every time I restart the RPI3+ (slave), otherwise the adapter stays red.

**Comment by schlaubstar** [comment]
@mrbungle64 I must also confirm that the adapter is very "delicate" considering it's "survive reboot stability". Today I updated the js-controller and switchbot.ble stayed red. Also running on RPI3+.

**Comment by mrbungle64** [comment]
@schlaubstar @capitaenz 

What os and what version of Node.js are you running on your RPI3+?

**Comment by schlaubstar** [comment]
my setup:
os: Raspbian GNU/Linux 11 (bullseye)
Node.js: v18.17.1(18.19.1)
NPM: 10.2.5

I just did a sudo-reboot and the whole device / iobroker and switchbot-ble restarted sucessfully.
After updating js-controller, iob deactivated the switchbot-ble instance proclaiming it caused a restart-loop.
I tried to run npm install, solely - but this did not help. 
I had to run the whole routine including "sudo rm -r node_modules/" before I could sucessfully restart the instance this morning.

**Comment by mrbungle64** [comment]
@schlaubstar @capitaenz 

Please post the following output:

```bash
cd /opt/iobroker/node_modules
npm list @abandonware/noble
```

**Comment by schlaubstar** [comment]
`user@rpi3b:/opt/iobroker/node_modules $ npm list @abandonware/noble
iobroker.inst@3.0.0 /opt/iobroker
├── @abandonware/noble@1.9.2-23 extraneous
├─┬ iobroker.switchbot-ble@0.4.9 (git+ssh://git@github.com/mrbungle64/ioBroker.switchbot-ble.git#f5289c9a20fc854aff1e7804a4e6f35a4adb7401)
│ └─┬ node-switchbot@1.10.0
│   └── @abandonware/noble@1.9.2-23
└─┬ node-switchbot@1.10.0 extraneous
  └── @abandonware/noble@1.9.2-23 deduped
`

**Comment by mrbungle64** [comment]
@schlaubstar 

It may help to delete the directories of `@abandonware/noble` and `node-switchbot` in `/opt/iobroker/node_modules`

**Comment by schlaubstar** [comment]
@mrbungle64 I did as advised and manually restarted the instance in the admin gui.
Will keep an eye on it and report.

**Comment by mrbungle64** [comment]
@schlaubstar @capitaenz 

I forgot to mention that after deleting the directories it's also a good idea to install the latest version of the switchbot-ble adapter from GitHub 😉

**Comment by capitaenz** [comment]
@mrbungle64

I have an RPI 3B+ as a slave
Node.js v18.17.1

I deleted the directories mentioned above and installed the adapter in version 0.4.9.
I will watch it.

Thanks for the help

**Comment by capitaenz** [comment]
The problem seems to be solved now! Thanks!
