### ISSUE TITLE
MagicSwitchBot

### ISSUE THREAD

**Issue by janhp** [mrbungle64/ioBroker.switchbot-ble#4]
Any chance you can create a similar adapter for the "[MagicSwitchBot](https://de.aliexpress.com/item/1005001907307014.html?src=google&albch=shopping&acnt=494-037-6276&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&&albagn=888888&albcp=1705854617&albag=67310370915&trgt=743612850714&crea=de1005001907307014&netw=u&device=c&albpg=743612850714&albpd=de1005001907307014&gclid=CjwKCAiAo5qABhBdEiwAOtGmbmfb_PVhf-YRZCgC5T4hfHF3LltU-BbPOP_EDtRRIjpBF7vwHXGD3hoCZBwQAvD_BwE&gclsrc=aw.ds)"? Would be awesome!

Thanks in advance

**Comment by mrbungle64** [comment]
@janhp 
No, I don't have any plans to create another adapter for such devices.
