### ISSUE TITLE
Possibility for bigger polling intervals and sensor calibration / offset?

### ISSUE THREAD

**Issue by schlaubstar** [mrbungle64/ioBroker.switchbot-ble#433]
### The question

Hi mrbungle64 - at first a big thanks for your efforts as it is really great to have a direct integration of the Switchbot devices without any HUB or cloud service needed. I really appreciate your adapter which worked flawlessly out of the box.

However I would have two questions or feature requests :

- I currently only use Temperature/Humidity Sensors where I could live with a refresh rate of 300 or even more seconds. Would it be possible to allow larger intervals in the adapter than 60 seconds? 

- I own tow "SwitchBot Meter Plus" and as fortune did not like me, they are 0,4°C apart, with an accuracy of 0,2°C. The manufacturer describes that you can calibrate the sensors (actually add an offset that can be added/substracted) and I assume it will be transmitted back to the device as the local display also needs to be updated. Of course one could do the math in IoBroker but it would be great if there was a way to submit the offset to the corresponding device using your adapter. Do you see a chance to implement this "calibration" feature ? 

https://support.switch-bot.com/hc/en-us/articles/360038378253

Thank you so much and best regards

**Comment by mrbungle64** [comment]
Hi @schlaubstar 

I'll try to add that features in the near future

**Comment by mrbungle64** [comment]
@schlaubstar 

Please try version 0.4.9

I added states for each device to set the offset values:

* offset.temperature
* offset.temperatureF
* offset.humidity

I also added 120, 180 and 300 seconds to the time interval options

**Comment by schlaubstar** [comment]
@mrbungle64 First of all, a happy new year and thank you for the quick reaction & implementation.

At first, when installing 0.4.9 I end up in the typical issue after upgrading or rebooting

`<html><body>

switchbot-ble.0 | 2024-01-06 12:06:00.446 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
switchbot-ble.0 | 2024-01-06 12:06:00.381 | error | Exception-Code:  MODULE_NOT_FOUND: Cannot find module  '../build/Release/bluetooth_hci_socket.node'Require stack:-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/index.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/with-custom-binding.js-  /opt/iobroker/node_modules/@abandonware/noble/index.js-  /opt/iobroker/node_modules/node-switchbot/lib/switchbot.js-  /opt/iobroker/node_modules/iobroker.switchbot-ble/main.js
switchbot-ble.0 | 2024-01-06 12:06:00.379 | error | Error:  Cannot find module '../build/Release/bluetooth_hci_socket.node'Require  stack:-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/index.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/with-custom-binding.js-  /opt/iobroker/node_modules/@abandonware/noble/index.js-  /opt/iobroker/node_modules/node-switchbot/lib/switchbot.js-  /opt/iobroker/node_modules/iobroker.switchbot-ble/main.js    at  Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)    at  Module._load (node:internal/modules/cjs/loader:922:27)    at  Module.require (node:internal/modules/cjs/loader:1143:19)    at require  (node:internal/modules/cjs/helpers:121:18)    at  Object.<anonymous>  (/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:2:30)     at Module._compile (node:internal/modules/cjs/loader:1256:14)    at  Module._extensions..js (node:internal/modules/cjs/loader:1310:10)    at  Module.load (node:internal/modules/cjs/loader:1119:32)    at  Module._load (node:internal/modules/cjs/loader:960:12)    at  Module.require (node:internal/modules/cjs/loader:1143:19)
switchbot-ble.0 | 2024-01-06 12:06:00.374 | error | unhandled  promise rejection: Cannot find module  '../build/Release/bluetooth_hci_socket.node'Require stack:-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js-  /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/index.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js-  /opt/iobroker/node_modules/@abandonware/noble/with-custom-binding.js-  /opt/iobroker/node_modules/@abandonware/noble/index.js-  /opt/iobroker/node_modules/node-switchbot/lib/switchbot.js-  /opt/iobroker/node_modules/iobroker.switchbot-ble/main.js
switchbot-ble.0 | 2024-01-06 12:06:00.371 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>`

..which I could fix using your Troubleshooting guide, actually by just calling `npm install`  in `/opt/iobroker/node_modules/iobroker.switchbot-ble/` but somehow your adapter really is a little 'delicate' when it comes to restarts or updates, at least on my installation ;-)

To your changes:
I tested the offset datapoints per device using integer as well as decimals for temperature and humidity, positive and negative values,  and confirm them to be working perfectly. Thanks a lot.

However: i receive one strange "info-type" log entry for the new datapoints:
`<html><body>

switchbot-ble.0 | 2024-01-06 12:32:32.639 | info | State value to set for "switchbot-ble.0.fb:ex:xx:xx:xx:xx.offset.humidity" has to be type "number" but received type "string"
-- | -- | -- | --

</body>
</html>
`
but this does not seem to affect the functionality

And I tested the new intervals, which are also working fine ! Thanks  a lot !

**Comment by mrbungle64** [comment]
@schlaubstar 

Thanks for your feedback 👍🏻  I'm glad the requested features work as expected.

> However: i receive one strange "info-type" log entry for the new datapoints:

I still need to fix this, but it should only appear when the new states are first created.
