### ISSUE TITLE
Reaktionszeit

### ISSUE THREAD

**Issue by Day1983** [mrbungle64/ioBroker.switchbot-ble#5]
Hallo,

ich habe den Switchbot mir gekauft und hab deinen Adapter verwendet. er ist auch grün und der Objektbau ist auch da.

Wenn ich auf Press drücke, dauert es sehr lange, bis der Bot reagiert - kann man hier was einstellen?
Teilweise sind es 20sec bis über 1Min!

Vielen Dank.

![image](https://user-images.githubusercontent.com/77491820/109815306-c9730e80-7c2f-11eb-8a0d-a397ca6a0ef3.png)

**Comment by mrbungle64** [comment]
Hallo @Day1983 

ich würde dann bei "Auf Geräte warten" einen höheren Wert empfehlen.
Bei mir sind da z.B. 2000 ms eingestellt.

Da beim Schalten immer zurest eine neue Verbindung aufgebaut wird kann es aber je nach Verbindungsqualität totzdem immer mal ein paar Sekunden dauern bis die hergestellt wurde und dann geschaltet wird.

**Comment by mrbungle64** [comment]
@Day1983 
Hast Du es mal ausprobiert?

**Comment by Day1983** [comment]
Hallo,

sorry, hat nicht dei zeit gefunden zu testen.
Der Bot läuft jetzt, sind so 10sec Wartezeit - einzig die begrenzung (kraft) is nervig.

Der Bot soll meine Gegensprechanlage (Mietshaus) drücken, leider drückt der Den Türknopf nicht festgenug. Hab noch keine Lösung hierfür.
Der Fahrweg des Bot ist mehr als ausreichend, aber anscheinend hat der Bot eine Kraftbegrenzung, oder sowas ähnliches. Leider öffnet die Tür nicht...
Idee?

**Comment by mrbungle64** [comment]
@Day1983 
Du meinst, dass da vielleicht eine Begrenzung von der Firmware her eingestellt ist?
Falls ja kann ich da aber leider nichts machen ...
