### ISSUE TITLE
Switchbot Mini

### ISSUE THREAD

**Issue by MichaelRoling1310** [mrbungle64/ioBroker.switchbot-ble#52]
### The question

Hallo
Ist es in Planung das der SwitchBot Mini auch unterstützt wird? Das wäre eine tolle Sache.
Vielen Dank für deine Arbeit

**Comment by mrbungle64** [comment]
Hallo  @MichaelRoling1310

> Ist es in Planung das der SwitchBot Mini auch unterstützt wird?

nein, da das hier die BLE Variante und somit der "falsche" Adapter dafür ist 😉 
Siehe "Before you install" Abschnitt:
https://github.com/mrbungle64/ioBroker.switchbot-ble#before-you-install

Das [hier](https://github.com/DrozmotiX/ioBroker.switchbot-hub) wäre dann der richtige Adapter für dich.

**Comment by MichaelRoling1310** [comment]
Vielen Dank für die Info

Gesendet: Samstag, 06. November 2021 um 15:44 Uhr
Von: "Sascha" ***@***.***>
An: "mrbungle64/ioBroker.switchbot-ble" ***@***.***>
Cc: "MichaelRoling1310" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [mrbungle64/ioBroker.switchbot-ble] Switchbot Mini (Issue #52)


 

Hallo @MichaelRoling1310


Ist es in Planung das der SwitchBot Mini auch unterstützt wird?


nein, da das hier die BLE Variante und somit der "falsche" Adapter dafür ist 😉
Siehe "Before you install" Abschnitt:
https://github.com/mrbungle64/ioBroker.switchbot-ble#before-you-install

Das hier wäre dann der richtige Adapter für dich.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
