### ISSUE TITLE
Keine Verbindung

### ISSUE THREAD

**Issue by pforrmi** [mrbungle64/ioBroker.switchbot-ble#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Adapter baut leider keine Verbindung aus. Troubleshoot schon ausprobiert...

[https://bilderupload.org/image/8d3054186-bildschirmfoto-2021-11-10.png](https://bilderupload.org/image/8d3054186-bildschirmfoto-2021-11-10.png)

### Version of the JS controller

3.3.18

### Version of Node.js

12.22.7

### Operating system

Linux

**Comment by mrbungle64** [comment]
@pforrmi

Ich kann mit den wenigen Infos leider nicht viel anfangen ...

> Troubleshoot schon ausprobiert...

Auch die Hinweise zur Installation beachtet?

>  I have searched the existing issues and no issue is describing my issue

Weicht dein (grundsätzliches) Problem hiervon ab?
[Adapter bleibt gelb, verbindet nicht mit Gerät](https://github.com/mrbungle64/ioBroker.switchbot-ble/issues/24)

> https://bilderupload.org/image/8d3054186-bildschirmfoto-2021-11-10.png

Bitte noch auf Debug Level stellen - ansonsten bringt mir der Auszug aus dem Log nicht viel
