### ISSUE TITLE
Switchbot Curtain

### ISSUE THREAD

**Issue by strombert** [mrbungle64/ioBroker.switchbot-ble#6]
Hallo, 
erstmal danke für den super Adapter!
Ich suche gerade eine Lösung für den Switchbot Curtain - kannst du den auch einfügen?
Danke!

**Comment by mrbungle64** [comment]
Hallo @strombert 

ich habe aktuell keine Pläne die Steuerung für den Curtain zu implementieren, da ich selbst keinen in Benutzung habe und das aktuell auch nicht plane.
Die Werte sollten allerdings schon mit der aktuellen Version ausgelesen und in die Datenpunkte eingetragen werden.

Für das Auslesen der Werte benutze ich die [node-switchbot](https://www.npmjs.com/package/node-switchbot) Library (welche den Curtain unterstützt) - für das Steuern benutze ich allerdings eine [andere](https://www.npmjs.com/package/switchbot) Library - diese unterstützt aber den Curtain nicht. Ich müsste da wahrscheinlich ein bisschen was umbauen - könnte die Steuerung mit dem Curtain aber selbst nicht testen. Dazu kommt noch, dass die "node-switchbot" Library bei mir damals nicht zuverlässig funktioniert hatte (weswegen ich mich dann für die andere entschieden habe).
