### ISSUE TITLE
Wert der ID switchMode kann im IOBroker nicht überschrieben werden

### ISSUE THREAD

**Issue by Pr0xyChainZ** [mrbungle64/ioBroker.switchbot-ble#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo mrbungle64,

der Wert der ID "switchMODE" kann in IOBroker nicht überschrieben werden. Habe versucht den Wert auf "true" zu überschreiben um den Switch Mode des Switchbots zu nutzen dieser wird jedoch kurz nach setzen des Werts wieder auf "false" überschrieben. Der Switchbot kann somit nur im Pressmode betrieben werden. 
<img width="1077" alt="Switch Mode lässt sich nicht aktivieren" src="https://user-images.githubusercontent.com/95136026/143686207-10066b0e-2bb7-44a3-b608-10262f70cd20.PNG">
  

### Version of the JS controller

3.3.19

### Version of Node.js

v12.22.7

### Operating system

Linux

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Ist der Modus in der Switchbot Mobile App korrekt eingestellt?

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

Habe den Switchbot ausschließlich über deinen  BLE-Adapter integriert. Dachte ich komme ohne die App und Bridge aus...

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Habe den Switchbot ausschließlich über deinen BLE-Adapter integriert. Dachte ich komme ohne die App und Bridge aus...

Die Bridge (bzw. Hub) benötigst Du nicht, aber es gibt ein paar Einstellungen die man (aktuell) nur über die App machen kann (z.B. den "Switch mode" einstellen). Die verwendete [Library](https://www.npmjs.com/package/node-switchbot) kann das meines Wissens nach nicht.

**Comment by Pr0xyChainZ** [comment]
Ah okay soetwas hatte ich mir schon gedacht. :( Dann muss ich mich wohl oder übel doch anmelden. Vielen Dank, der Issue kann geschlossen werden. VG
