### ISSUE TITLE
Wert der ID position (Switchbot Curtain) kann nicht überschrieben werden

### ISSUE THREAD

**Issue by Pr0xyChainZ** [mrbungle64/ioBroker.switchbot-ble#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo Sascha,

ich nochmal. ;) Ich nehme an der Wert der ID Position (beim Switchbot Curtain) sprich das Öffnen und Schließen des Vorhangs ist über IOBroker noch nicht möglich? (wie auch schon zuvor der Wechsel bei "Press Mode" und "Switch Mode"). 

Der Switchbot funktioniert inzwischen wie er soll. Vielen Dank dafür! 👍  

### Version of the JS controller

3.3.19

### Version of Node.js

v12.22.7

### Operating system

Linux

**Comment by mrbungle64** [comment]
Hi @Pr0xyChainZ 

ja, wie in der [Readme erwähnt](https://github.com/mrbungle64/ioBroker.switchbot-ble#other-models-untested) ist der Curtain bisher nur "read-only":

#### Other models (untested)
* SwitchBot "Curtain" (read-only)

Wenn die Library das irgendwann kann, werde ich versuchen es zu implementieren.

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Ich habe gesehen, dass die Library das inzwischen unterstützt. Da ich selbst keinen Curtain habe hatte ich das nicht so auf dem Zettel. Ich schaue mir das im Laufe des Tages mal genauer an.

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

Hey super, das klingt super! Ich stelle mich gerne als Tester zur Verfügung. :) Ich hatte mich ein wenig von www.verdrahtet.info verwirren lassen (siehe Artikel https://www.verdrahtet.info/2021/09/07/switchbot-im-kurztest-was-koennen-die-kleinen-geraete/). Dachte der Curtain sowie der Switchbot ließe sich schon komplett und problemlos über iobroker steuern.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Hey super, das klingt super! Ich stelle mich gerne als Tester zur Verfügung. :) Ich hatte mich ein wenig von [www.verdrahtet.info](http://www.verdrahtet.info) verwirren lassen (siehe Artikel https://www.verdrahtet.info/2021/09/07/switchbot-im-kurztest-was-koennen-die-kleinen-geraete/). Dachte der Curtain sowie der Switchbot ließe sich schon komplett und problemlos über iobroker steuern.

Er sagt, dass der Curtain auch "auftaucht" - nicht dass der sich steuern lässt.
Und er sagt auch, dass der lt. der GitHub Seite nur "Bot" und "Meter" unterstützt werden.

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

> @mrbungle64
> 
> Hey super, das klingt super! Ich stelle mich gerne als Tester zur Verfügung. :)

Bitte installier' den Adapter mal mit folgendem Link:
https://github.com/mrbungle64/ioBroker.switchbot-ble/tree/Feature-branch

Dann sollten Datenpunkte zum Steuern erstellt werden ("open", "close", "pause", "runToPos") und die könnten im Optimalfall dann auch schon funktionieren 😉

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

Oh das ging fix. :) Ich konnte leider heute nicht früher testen. Ich habe eben den Adpter rausgeworfen und den Objektbaum des Adapters gelöscht und danach den Future Branch installiert. Bei den neuen IDs lassen sich jetzt auch die Buttons bedienen bzw. wenn ich auf "text" umstelle auf True und False setzen (siehe Screenshot). Auch bei der  ID "runToPos" wird der Wert übernommen leider jedoch keine Aktion ausgelöst. Der Curtain bewegt sich keinen Zentimeter. :(

<img width="1097" alt="Switchbot Curtain" src="https://user-images.githubusercontent.com/95136026/143791454-28d38633-e2b9-4eca-9e66-54dec5a856c0.PNG">

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> ... Bei den neuen IDs lassen sich jetzt auch die Buttons bedienen 

Heißt das, dass die Buttons funktionieren? Werden "open" und "close" korrekt am Gerät ausgeführt?

> bzw. wenn ich auf "text" umstelle auf True und False setzen (siehe Screenshot).

Warum tust du das?

Die Rolle der vom Adapter erstellen Datenpunkte sollte nie (außer in seltenen Ausnahmefällen vielleicht) vom Benutzer geändert werden.

> Auch bei der ID "runToPos" wird der Wert übernommen leider jedoch keine Aktion ausgelöst. Der Curtain bewegt sich keinen Zentimeter. :(

Das muss ich mir dann wohl noch mal anschauen ...

Was erscheint denn im Log? Du musst ggf. auf Debug Level stellen - aber schau bitte erst mal ohne das ...

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

> Heißt das, dass die Buttons funktionieren? Werden "open" und "close" korrekt am Gerät ausgeführt?

Leider nein, es lässt sich nur der Zustand / Wert überschreiben.


> Warum tust du das?

Ich hatte erst nach dem Test der Buttons auf text gewechselt weils für mich besser ersichtlich war. ;)


> Die Rolle der vom Adapter erstellen Datenpunkte sollte nie (außer in seltenen Ausnahmefällen vielleicht) vom Benutzer geändert werden.

Okay werde ich demnächst beachten. Hatte da bei selbst erstellten Datenpunkten und bei anderen bisher keine Probleme.
 

> Was erscheint denn im Log? Du musst ggf. auf Debug Level stellen - aber schau bitte erst mal ohne das ...

Ich hoffe ich habe es richtig gemacht und der Log ist verwendbar. Unterhalb ein Ausschnitt des Logs der Switchbot-ble Instanz (ausführlicher Ausschnitt im Anhang) als ich den Wert des Datenpunkts "runToPos" geändert habe:

2021-11-30 01:04:39.773 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.
2021-11-30 01:04:39.775 - info: switchbot-ble.0 (15482) [botAction] Will try again (1/15) ...
2021-11-30 01:04:39.775 - debug: switchbot-ble.0 (15482) [setNextInterval] cmd: runToPos
2021-11-30 01:04:39.776 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: false
2021-11-30 01:04:40.220 - debug: switchbot-ble.0 (15482) [execNextCmd] cmd: runToPos
2021-11-30 01:04:40.222 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: true
2021-11-30 01:04:40.324 - debug: switchbot-ble.0 (15482) [botAction] Connecting to device f2:dd:6c:85:93:c3 ...
2021-11-30 01:04:40.843 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.
2021-11-30 01:04:40.844 - info: switchbot-ble.0 (15482) [botAction] Will try again (2/15) ...
2021-11-30 01:04:40.845 - debug: switchbot-ble.0 (15482) [setNextInterval] cmd: runToPos
2021-11-30 01:04:40.845 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: false
2021-11-30 01:04:41.220 - debug: switchbot-ble.0 (15482) [execNextCmd] cmd: runToPos
2021-11-30 01:04:41.222 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: true
2021-11-30 01:04:41.280 - debug: switchbot-ble.0 (15482) [botAction] Connecting to device f2:dd:6c:85:93:c3 ...
2021-11-30 01:04:41.764 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.
2021-11-30 01:04:41.765 - info: switchbot-ble.0 (15482) [botAction] Will try again (3/15) ...
2021-11-30 01:04:41.765 - debug: switchbot-ble.0 (15482) [setNextInterval] cmd: runToPos
2021-11-30 01:04:41.766 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: false
2021-11-30 01:04:42.220 - debug: switchbot-ble.0 (15482) [execNextCmd] cmd: runToPos
2021-11-30 01:04:42.220 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: true
2021-11-30 01:04:42.227 - debug: switchbot-ble.0 (15482) [botAction] Connecting to device f2:dd:6c:85:93:c3 ...
2021-11-30 01:04:42.748 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.
2021-11-30 01:04:42.749 - info: switchbot-ble.0 (15482) [botAction] Will try again (4/15) ...
2021-11-30 01:04:42.749 - debug: switchbot-ble.0 (15482) [setNextInterval] cmd: runToPos
2021-11-30 01:04:42.749 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: false
2021-11-30 01:04:43.220 - debug: switchbot-ble.0 (15482) [execNextCmd] cmd: runToPos
2021-11-30 01:04:43.221 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: true
2021-11-30 01:04:43.292 - debug: switchbot-ble.0 (15482) [botAction] Connecting to device f2:dd:6c:85:93:c3 ...
2021-11-30 01:04:43.850 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.
2021-11-30 01:04:43.851 - info: switchbot-ble.0 (15482) [botAction] Will try again (5/15) ...
2021-11-30 01:04:43.851 - debug: switchbot-ble.0 (15482) [setNextInterval] cmd: runToPos
2021-11-30 01:04:43.852 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: false
2021-11-30 01:04:44.220 - debug: switchbot-ble.0 (15482) [execNextCmd] cmd: runToPos
2021-11-30 01:04:44.221 - debug: switchbot-ble.0 (15482) [setIsBusy] isBusy: true
2021-11-30 01:04:44.239 - debug: switchbot-ble.0 (15482) [botAction] Connecting to device f2:dd:6c:85:93:c3 ...
2021-11-30 01:04:44.738 - warn: switchbot-ble.0 (15482) [botAction] Error while running deviceAction runToPos for device f2:dd:6c:85:93:c3: Error: No service was found.

[Switchbot Curtain Log.txt](https://github.com/mrbungle64/ioBroker.switchbot-ble/files/7621969/Switchbot.Curtain.Log.txt)

**Comment by mrbungle64** [comment]
@Pr0xyChainZ

> @mrbungle64
> 
> > Heißt das, dass die Buttons funktionieren? Werden "open" und "close" korrekt am Gerät ausgeführt?
> 
> Leider nein, es lässt sich nur der Zustand / Wert überschreiben.
> 
> > Warum tust du das?
> 
> Ich hatte erst nach dem Test der Buttons auf text gewechselt weils für mich besser ersichtlich war. ;)
> 
> > Die Rolle der vom Adapter erstellen Datenpunkte sollte nie (außer in seltenen Ausnahmefällen vielleicht) vom Benutzer geändert werden.
> 
> Okay werde ich demnächst beachten. Hatte da bei selbst erstellten Datenpunkten und bei anderen bisher keine Probleme.

Bei selbst erstellten Datenpunkten ist das ja auch in Ordnung.
Datenpunkte und Struktur der Adapter Instanzen sollten aber so bleiben wie der Adapter die angelegt hat.

> 
> > Was erscheint denn im Log? Du musst ggf. auf Debug Level stellen - aber schau bitte erst mal ohne das ...
> 
> Ich hoffe ich habe es richtig gemacht und der Log ist verwendbar. Unterhalb ein Ausschnitt des Logs der Switchbot-ble Instanz (ausführlicher Ausschnitt im Anhang) als ich den Wert des Datenpunkts "runToPos" geändert habe:
>

Ja, das war soweit in Ordnung. Ich habe das Logging aber noch mal erweitert, so dass man besser sehen kann was da passiert - und was nicht ...

Installier den Adapter noch mal über den folgenden Link neu:
https://github.com/mrbungle64/ioBroker.switchbot-ble/tree/Feature-branch
Vorher bitte noch mal den Objektbaum des Adapters komplett löschen.

Dann bitte noch mal ein Log schicken (bitte diesmal auf debug level "info").
Dann die Buttons "open", "close" und "pause" jeweils 1x ausführen und dann auch "runToPos" mit einem Wert auslösen.
Am besten jeweils immer so 10-20 Sekunden warten bis du den nächsten Befehl ausführst.

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

So, habe den Objektbaum gelöscht und den Adapter reinstalliert. Das Log-Level der Instanz wurde jetzt nicht auf debug gesetzt und auf Info belassen. Der Log wurde noch von den anderen Instanzmeldungen gesäubert (siehe Anhang).

[Switchbot Curtain Log 01.12.2021.txt](https://github.com/mrbungle64/ioBroker.switchbot-ble/files/7629868/Switchbot.Curtain.Log.01.12.2021.txt)

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

* Kam bei "pause" und "runToPos" sonst nichts mehr im Log?
* Ist der Curtain eigentlich in Reichweite vom ioBroker System?

**Comment by Pr0xyChainZ** [comment]
@mrbungle64 

Sorry, dass ich mich jetzt erst zurück melde. Die Woche war leider was stressig. 

Ich kann noch einmal einen Test durchführen, aber der Log war soweit vollständig. 
Der Raspi (interner BT-Adapter) steht ca. 1,50m vom Curtain entfernt und über die App ist er auch von mehreren Metern steuerbar.

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

> Ich kann noch einmal einen Test durchführen

Es wäre gut, wenn Du das noch mal machen könntest 👍🏻

**Comment by patrickbs96** [comment]
Bei mir klappt es manchmal, ich denke der raspberryPi ist einfach zu weit weg um eine ordentliche Verbindung aufzubauen. Da liegen aktuell ca. 10 Meter dazwischen.
Wollte mich in den nächsten Tagen eh um das Thema kümmern und hätte mich dazu programmiertechnisch daran gesetzt. Hatte nicht gesehen das dafür schon ein Feature-Branch existiert 😉 

Falls du jemanden für die Curtain brauchst zum programmieren oder testen kann ich da behilflich sein 😃

**Comment by mrbungle64** [comment]
@patrickbs96 

> Bei mir klappt es manchmal, ich denke der raspberryPi ist einfach zu weit weg um eine ordentliche Verbindung aufzubauen. Da liegen aktuell ca. 10 Meter dazwischen. Wollte mich in den nächsten Tagen eh um das Thema kümmern und hätte mich dazu programmiertechnisch daran gesetzt. Hatte nicht gesehen das dafür schon ein Feature-Branch existiert wink
> 
> Falls du jemanden für die Curtain brauchst zum programmieren oder testen kann ich da behilflich sein smiley

Hallo Patrick,

ja gerne 👍🏻 Ich habe gerade mal den Feature Branch in den master gemerged.

Du kannst gerne Pull Requests erstellen und auch insgesamt gerne am Adapter mitwirken.
Würde ich begrüßen 👍🏻

**Comment by Pr0xyChainZ** [comment]
Sorry habe gerade aufgrund eines Jobwechsels nicht so viel Zeit. Ich habe jetzt nochmal alle Aktionen ausgeführt (der Adapter wurde neu installiert (diesmal nicht den Feature Branch, da ja die Feature Branch in den Master gemerged wurde) und die Dtanepunkte entfernt). Im Anhang das neue Log. Es tat sich leider wie erwartet nichts.

[Switchbot Curtain Log 12.12.2021.txt](https://github.com/mrbungle64/ioBroker.switchbot-ble/files/7698760/Switchbot.Curtain.Log.12.12.2021.txt)

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Da war noch ein Bug, dass nach der max. Anzahl von Versuchen der Zähler nicht zurückgesetzt wurde.
Diesen Fehler habe ich jetzt dann gefixt. Du kannst es nun noch mal mit der aktuellen Version versuchen.
Der `No service was found` Fehler wird allerdings davon eher nicht behoben sein.

**Comment by patrickbs96** [comment]
Ich habe den Pi bei mir einmal um positioniert und jetzt klappt es schon zuverlässiger. Manchmal aber auch erst, wenn der Zähler die 15 erreicht hat oder auch manchmal gar nicht... Irgendwie komisch das die Verbindung so schlecht ist über die App klappt es sofort...

Im Vergleich zu @Pr0xyChainZ kriege ich nur die Fehlermeldung `Failed to discover services and characteristics: DISCONNECTED`, wenn die Verbindung nicht aufgebaut werden konnte.

**Comment by mrbungle64** [comment]
@patrickbs96 

Ich habe noch mal ein paar Optimierungen vorgenommen und 2 neue Optionen den Adapter Einstellungen hinzugefügt.
Schau mal bitte, ob das Steuern der Bots ("Curtain" und "Bot") nun zuverlässiger funktioniert.

**Comment by patrickbs96** [comment]
Es sieht definitiv so aus als klappt es jetzt besser 👍🏻 

Ich habe aber zwei Bugs gefunden:
1. Nachdem ich die neue Version installiert hatte hat ein Befehl wieder die 15/15 erreicht gehabt und hat dann abgebrochen. Danach hat er aber automatisch wieder gestartet aber bei jeder Ausführung einen Typeerror geschmissen (could not access Property connect of undefined). Der Befehl wurde dann immer wieder aufgerufen. Ich musste den Adapter dann neustarten, da er nicht aufgehört hatte. Leider hatte ich das Log schon gelöscht gehabt...
2. Heute morgen wurde laut Log nur das State change erkannt aber keine Aktion ausgeführt

**Comment by mrbungle64** [comment]
@patrickbs96 

zu 1.)
Da bräuchte ich mal ein Log bzw. mehr Informationen, da ich den Fehler (mit einem "Bot") nicht nachstellen kann.

zu 2.)
Diesen Fehler kenne ich glaub ich schon.
Da wird `[onStateChange] received command: command` geloggt, aber dann nichts weiter ausgeführt, richtig?
Das passiert recht selten, aber es kommt halt vor. Versuche schon seit Tagen die Ursache zu finden ...

**Comment by patrickbs96** [comment]
1) Ich habe die Stelle in meinem Fork einmal korrigiert. Ich vermute, dass die DeviceList nach dem Discover leer ist und beim Zugriff auf `bot.connect();` die Exception aufgetreten ist. Ich werde berichten ob ich es nochmal nachstellen konnte.

2) Ja genau, den hatte ich heute Morgen. War schade, weil sich die Gardinen dadurch leider nicht automatisch mit dem Wecker geöffnet haben 😆

**Comment by mrbungle64** [comment]
@patrickbs96 

Könntest du direkt mal einen Pull Request erstellen?
Ich habe gesehen, dass Du noch mehr geändert/korrigiert hast.
Das erscheint mir sinnvoll 😉

**Comment by mrbungle64** [comment]
@mrbungle64 

Ich hab deinen Pull Request gemerged und den Stand soweit auch schon bei mir installiert.

Ich würde als nächstes eine Queue Klasse implementieren, so dass wir damit den 2. Fehler auch in den Griff bekommen. Ich denke, dass ich verstanden habe warum der auftritt.

**Comment by patrickbs96** [comment]
@mrbungle64 Ich sehe was du meinst, in dem Objekt wird der letzte Befehl gespeichert und falls dieser identisch ist wird er verworfen..

**Comment by mrbungle64** [comment]
> @mrbungle64 Ich sehe was du meinst, in dem Objekt wird der letzte Befehl gespeichert und falls dieser identisch ist wird er verworfen..

Nicht ganz 😉 Ich denke da wird der scanDevices Befehl ab und zu mal dem gesendeten Befehl das Intervall klauen.

Ich bin aktuell dabei die Queue zu implementieren. Dazu habe ich wieder einen separaten branch angelegt.
Ich hoffe, dass ich spätestens zum Wochenende soweit bin das in den master branch zu mergen.

**Comment by mrbungle64** [comment]
@patrickbs96 

Ich habe eben die Version 0.3.5 released.
Bisher hatte ich beim Testen keine Aussetzer mehr. Bin gespannt auf Dein Feedback 😉

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Hat sich bei Dir inzwischen was getan? Da scheint ja irgendwas anderes quer zu hängen ...

**Comment by patrickbs96** [comment]
@mrbungle64 

Fühlt sich definitiv auch flüssiger an als vorher 👍🏻 zwar kriege ich immernoch 1-3 Warnung beim Ausführen aber ansonsten klappt es jetzt 😃 

Ich habe einen kleinen Bug gefunden als ich nach einem Neustart den ersten Befehl ausgeführt hatte bevor die Devices geladen waren: `[commandInterval] error while running command: TypeError: Cannot read property 'on' of undefined`

**Comment by mrbungle64** [comment]
@patrickbs96 

> @mrbungle64
> 
> Fühlt sich definitiv auch flüssiger an als vorher 👍🏻

Das hört sich gut an 👍🏻  Deckt sich mit meinen aktuellen Erfahrungen.

> zwar kriege ich immernoch 1-3 Warnung beim Ausführen aber ansonsten klappt es jetzt smiley

Ich denke das sind (wenn dann) eher Issues in der Library, aber es gibt trotzdem bestimmt noch Optimierungspotenzial 😉 

> 
> Ich habe einen kleinen Bug gefunden als ich nach einem Neustart den ersten Befehl ausgeführt hatte bevor die Devices geladen waren: `[commandInterval] error while running command: TypeError: Cannot read property 'on' of undefined`

Der ist bei mir auch schon aufgetreten - habe die Ursache aber bisher noch nicht gefunden ...

**Comment by patrickbs96** [comment]
@mrbungle64 

> Ich denke das sind (wenn dann) eher Issues in der Library, aber es gibt trotzdem bestimmt noch Optimierungspotenzial 😉
Ja das denke ich auch 😃 

> Der ist bei mir auch schon aufgetreten - habe die Ursache aber bisher noch nicht gefunden ...
Ich habe einen Pullrequest für den Typeerror erstellt, müsste die Stelle gewesen sein 😉

**Comment by mrbungle64** [comment]
@patrickbs96 

> Ich habe einen Pullrequest für den Typeerror erstellt, müsste die Stelle gewesen sein wink

Danke Dir! 👍🏻  Ich habe eben darauf basierend die Version 0.3.6 released

**Comment by mrbungle64** [comment]
@patrickbs96 

Ich denke wir können den "Curtain" jetzt als grundsätzlich steuerbar ansehen, oder?

Ich hatte es jetzt auch kein einziges Mal, dass der Bot zwischendurch mal nicht reagiert. Das scheint jetzt sehr zuverlässig zu funktionieren.

@Pr0xyChainZ 

Hattest Du noch mal die Gelegenheit die aktuelle Version zu testen?

**Comment by patrickbs96** [comment]
@mrbungle64 
Ja würde ich sagen, ich steuere meinen nur noch so und es klappt jetzt bei jeder Ausführung. 
Manchmal etwas länger bis es ausgeführt wird, da es nicht immer beim ersten Mal klappt aber dafür kann man ja die Wiederholungen einstellen 😉

**Comment by Pr0xyChainZ** [comment]
> @patrickbs96
> 
> Ich denke wir können den "Curtain" jetzt als grundsätzlich steuerbar ansehen, oder?
> 
> Ich hatte es jetzt auch kein einziges Mal, dass der Bot zwischendurch mal nicht reagiert. Das scheint jetzt sehr zuverlässig zu funktionieren.
> 
> @Pr0xyChainZ
> 
> Hattest Du mal die Gelegenheit die aktuelle Version zu testen?

@mrbungle64 

Sorry, dass ich mich jetzt erst melde. Ich habe eben die alte Version 0.3.5 deinstalliert und clean die 0.3.7 installiert. 

Alle Wartezeiten wurden auf Max gestellt und wieder einen Test gefahren. Alle Änderungen der Werte haben keine Aktion des Switchbot Curtains zur Folge (im Log kommt bei jedem Versuch der Fehler "Error: no service was found")... 

Mein Switchbot Button hingegen funktioniert wie auch schon mit den Vorversionen problemlos. Der Button hat sogar eine schlechtere Signalstärke als der Curtain (rssi -57 (Curtain rssi -53). Ich verwende den Sitchbot Curtain U-Rail2. Möglicherweise unterscheidet er sich zu den anderen Modellen. Ich kann mir jedenfalls nicht erklären wie es ansonsten bei @patrickbs96 funktionieren soll. 

Über die Switchbot App kann ich den curtain jedenfalls problemlos steuern (Aktionen werden umgehend umgesetzt).

**Comment by patrickbs96** [comment]
Hm das ist wirklich komisch... Also am Modell kann es leider nicht liegen, da ich auch den Curtain U-Rail2 habe... An der Signalstärke auch nicht, da mein Curtain einen schlechteren Wert (RSSI -82) hat... Welchen Raspi hast du denn im Einsatz?
Es ist schon sehr komisch, dass der Button funktioniert aber der Curtain nicht.. Ich habe auch beide im Einsatz.

Meine Adminseite sieht wie folgt aus, falls es hilft:
![image](https://user-images.githubusercontent.com/49351462/147737303-d0664cbf-2d46-4328-865c-962292eb7436.png)

@mrbungle64 Ich habe Mal Google angeschmissen und diese GitHub Issues gefunden. Die scheinen beide mit dem [Node-switchbot](https://github.com/OpenWonderLabs/node-switchbot) zu tun zu haben:
https://github.com/OpenWonderLabs/node-switchbot/issues/12
https://github.com/zizi4n5/homebridge-switchbot-for-mac/issues/9

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Hast Du den Post von @patrickbs96 gesehen?

**Comment by mrbungle64** [comment]
@Pr0xyChainZ 

Falls das Problem mit den Einstellungen aus dem Screenshot von @patrickbs96 noch besteht würde ich Dich bitten einen neuen Issue zu erstellen, da die grundsätzliche Unterstützung für den Curtain ja seit spätestens Ende Dezember 21 geben ist.

Diesen Issue hier würde ich nun gerne (ab-)geschlossen lassen.

**Comment by mrbungle64** [comment]
@Pr0xyChainZ @patrickbs96 

Hat einer von Euch beim Curtain schon die Firmware-Version 3.9 installiert?

Mit dieser Firmware scheint es [Probleme](https://github.com/OpenWonderLabs/node-switchbot/issues/101) zu geben.

Falls Ihr noch eine niedrigere Version installiert habt würde ich erst mal von einem Update abraten.
Ansonsten würde ich mich über Feedback freuen, wie es mit der Firmware-Version 3.9 funktioniert 😉
