### ISSUE TITLE
Failed to discover services and characteristics: DISCONNECTED

### ISSUE THREAD

**Issue by JayP666** [mrbungle64/ioBroker.switchbot-ble#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,

ich bekomme beim Absenden einer Action folgende Meldung im Log und es wird nichts ausgeführt.
[botAction] Error while running deviceAction press for device f0:f8:0f:6f:7d:6e: Error: Failed to discover services and characteristics: DISCONNECTED

Viele Grüße
Jay

### Version of the JS controller

3.3.21

### Version of Node.js

v14.18.2

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
[botAction] Error while running deviceAction press for device f0:f8:0f:6f:7d:6e: Error: Failed to discover services and characteristics: DISCONNECTED
```

**Comment by mrbungle64** [comment]
@JayP666 

Bitte den Adapter mal mit folgender URL installieren:
https://github.com/mrbungle64/ioBroker.switchbot-ble/tree/Feature-branch

Dann den kompletten Objektbaum löschen und Adapter Instanz (neu) starten.

Falls es dann immer noch so sein sollte:
- Befindet sich der Bot in Reichweite des ioBroker Systems (<10m bzw. möglichst keine Wände dazwischen)?
- Der Adapter versucht bis zu 15x den Befehl auszuführen. Tut er das und ist das immer erfolglos?
- Läuft auf dem System noch andere Software welche die Bluetooth Schnittstelle in Anspruch nimmt (z.B. der BLE Adapter)?

**Comment by mrbungle64** [comment]
Keine Antwort bekommen
