### ISSUE TITLE
Adapter bleibt gelb und findet kein Gerät

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.switchbot-ble#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Moin zusammen,

ich habe mir einen Switchbot gekauft und leider bleibt der Adapter gelb.
Ich habe die Version 0.3.7 installiert auf einem Raspberry als Slave.
Der Slave hat einen USB/WLAN Dongle und es läuft auf diesem erfolgreich der ble-Adapter.
Folgende Einträge bekomme ich im Log:

`switchbot-ble.0
2022-01-11 19:05:11.968	error	[scanDevices] error: Error: Failed to initialize the Noble object: poweredOff

switchbot-ble.0
2022-01-11 19:05:06.928	info	starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.switchbot-ble, node: v14.18.2, js-controller: 3.3.22

switchbot-ble.0
2022-01-11 19:04:59.774	info	Got terminate signal TERMINATE_YOURSELF`

Was kann ich tun?

VG
Leif

### Version of the JS controller

3.3.22

### Version of Node.js

14.18.2

### Operating system

Linux

**Comment by mrbungle64** [comment]
@capitaenz 

Wie schaut es aus, wenn Du den BLE-Adapter mal stoppst?

**Comment by capitaenz** [comment]
@mrbungle64 
Ich habe den ble-Adapter gestoppt, den Switchbot-Adapter neu gestartet und bekomme den gleichen Fehler.

Ich kann auf dem Slave dieses Verzeichnis nicht finden:
/opt/iobroker/node_modules/iobroker.switchbot-ble/
!?

**Comment by capitaenz** [comment]
@mrbungle64 

ich hab das Problem...
Ich installiere auf dem Slave:

![instanz](https://user-images.githubusercontent.com/1240236/149001311-1bd4974d-b885-48ba-909b-ddcb3b656b8f.JPG)

Aber er istalliert dann auf dem Hauptsystem!???

`$ iobroker add switchbot-ble auto --host debian-iobroker

host.debian-iobroker create instance switchbot-ble

host.debian-iobroker object switchbot-ble.0.info.connection created

host.debian-iobroker object switchbot-ble.0.info created

host.debian-iobroker object system.adapter.switchbot-ble.0.logLevel created

host.debian-iobroker object system.adapter.switchbot-ble.0.sigKill created

host.debian-iobroker object system.adapter.switchbot-ble.0.eventLoopLag created

host.debian-iobroker object system.adapter.switchbot-ble.0.outputCount created

host.debian-iobroker object system.adapter.switchbot-ble.0.inputCount created

host.debian-iobroker object system.adapter.switchbot-ble.0.uptime created

host.debian-iobroker object system.adapter.switchbot-ble.0.memRss created

host.debian-iobroker object system.adapter.switchbot-ble.0.memHeapTotal created

host.debian-iobroker object system.adapter.switchbot-ble.0.memHeapUsed created

host.debian-iobroker object system.adapter.switchbot-ble.0.cputime created

host.debian-iobroker object system.adapter.switchbot-ble.0.cpu created

host.debian-iobroker object system.adapter.switchbot-ble.0.compactMode created

host.debian-iobroker object system.adapter.switchbot-ble.0.connected created

host.debian-iobroker object system.adapter.switchbot-ble.0.alive created

host.debian-iobroker Set default value of switchbot-ble.0.info.connection: false

host.debian-iobroker object system.adapter.switchbot-ble.0 created

Process exited with code 0`

**Comment by mrbungle64** [comment]
@capitaenz 

Funktioniert es dann wenn Du es auf dem Slave direkt installierst?

**Comment by capitaenz** [comment]
OK, ich hab es... was ist passiert?

- Ich hatte den Adapter installiert, aber vergessen dies auf dem vis-raspi-wohnzimmer zu installieren.
- hab dann den auf dem Hauptsystem installierten Adapter gelöscht.
- nun ist der Adapter aus der Liste verschwunden!?
- ich musste über URL installieren.
- habe nun vis-raspi-wohnzimmer ausgewählt.
- Dein Adapter wurde aber weiterhin auf dem Hauptsystem installiert...
- Habe dann den Adapter gelöscht.
- Nun explizit den Slave ausgewählt und nach dem 2. Versuch den Adapter per URL zu installieren, ist er da und funktioniert.

Einen schönen Abend und viele Grüße
Leif
